#!/bin/sh
set -eu

cat > /usr/share/nginx/html/env-config.js <<EOF_CONFIG
window.__APP_CONFIG__ = {
  REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL}",
  REACT_APP_POSTHOG_KEY: "${REACT_APP_POSTHOG_KEY}",
  REACT_APP_POSTHOG_HOST: "${REACT_APP_POSTHOG_HOST}",
  REACT_APP_DEMO_MODE: "${REACT_APP_DEMO_MODE}"
};
EOF_CONFIG
